name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: azure/docker-login@v1
      with:
        #login-server: ${{ secrets.ACRSERVER }}
        login-server: scidemoacr.azurecr.io
        #username: ${{secrets.ACRUSERNAME}}
        username: SCIDEMOACR
        #password: ${{ secrets.ACRPASS }}
        password: TRMTpbms4SddkbYAAFfL=IU/b3EoE9hY
    
    - run: docker build . --file .devcontainer/Dockerfile --tag my-image-name:$(date +%s)
    - run: docker image push ${{secrets.ACRSERVER}}/SCI/my-image-name:$(date +%s)
