name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag my-image-name:$(date +%s)
      
    - name: ACR build
      id: acr
      uses: ams0/acr-task-github-action@v1
      with:
        service_principal: ${{ secrets.service_principal }}
        service_principal_password: ${{ secrets.service_principal_password }}
        tenant: ${{ secrets.tenant }}
        registry: ${{ secrets.registry }}
        repository: ${{ secrets.repository }}
        image: poi
        git_access_token: ${{ secrets.git_access_token }}
        folder: src/poi
        dockerfile: ../../dockerfiles/Dockerfile_3
