name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag scidemoacr.azurecr.io/my-image-name:$(date +%s)

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACRSERVER }}
        #login-server: scidemoacr.azurecr.io
        #username: ${{secrets.ACRUSERNAME}}
        username: SCIDEMOACR
        #password: ${{ secrets.ACRPASS }}
        password: TRMTpbms4SddkbYAAFfL=IU/b3EoE9hY
    - run: docker build . --file .devcontainer/Dockerfile --tag scidemoacr.azurecr.io/my-image-name:${{ github.sha }}
    - run: docker push scidemoacr.azurecr.io/my-image-name:${{ github.sha }}
        
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true
    - run: 'ls'
            
    - name: 'Deploy to Azure Container Instances'
      uses: azure/aci-deploy@v1
      with:
        resource-group: SCIDEMO
        dns-name-label: SCIDEMO${{ github.run_number }}
        image: scidemoacr.azurecr.io/my-image-name:${{ github.sha }}
        registry-login-server: scidemoacr.azurecr.io
        registry-username: SCIDEMOACR
        registry-password: TRMTpbms4SddkbYAAFfL=IU/b3EoE9hY
        name: aci-sampleapp
        location: 'North Europe'
    - run: 'ls'
